// Generated by CoffeeScript 2.7.0
(function () {
	var diffVec,
		ref,
		boundMethodCheck = function (instance, Constructor) {
			if (!(instance instanceof Constructor)) {
				throw new Error(
					"Bound instance method accessed before binding",
				);
			}
		};

	diffVec = v2.create();

	ref = window.Interpolator = function () {
		class Interpolator extends window.Sim {
			constructor() {
				super();
				this.think = this.think.bind(this);
				this.step = 0; // game step integer
				this.smoothStep; // game step as a float where fractional part is how long till next step
				this.advanceStep; // 1 if game advaned by one step, 0 if game is paused
				this.firstUpdate = true;
				this.things = {};
				this.players = [];
				this.particles = {};
				this.trails = {}; // keeps all the client side unit/proj trails
				this.avgFrame = 9;
				this.lastFrame = 0;
				this.stepTime = now();
				this.t = now();
				this.avgDt = 1 / 60;
				this.avgTime = 1000 / 16;
				this.allMessages = [];
				this.dataQ = [];
				this.wait = 0;
				this.prevWait = 2;
				this.state = "waiting";
				this.pref = {};
				this.zJson = new window.ZJson(prot.commonWords);
			}

			gameStarted() {
				if (!commander) {
					return;
				}
				//@recordReplay()
				this.players = [];
				this.things = {};
				this.particles = {};
				this.trails = {};
				this.winningSide = null;
				track("start");
				if (!sim.galaxyStar && !sim.local) {
					if (commander.side !== "spectators") {
						ui.go("battle");
					}
					if (ui.mode === "battleroom" || ui.mode === "quickscore") {
						ui.go("battle");
					}
				}
				// select nothing
				return (commander.selection = []);
			}

			focusMap() {
				var _, dist, maxDist, ref1, thing;
				maxDist = 0;
				ref1 = sim.things;
				for (_ in ref1) {
					thing = ref1[_];
					dist = v2.mag(thing.pos);
					if (dist > maxDist) {
						maxDist = dist;
					}
				}
				battleMode.focus = [0, 0];
				return (battleMode.zoom = maxDist / 1000);
			}

			gameEnded() {
				actionMixer.reset();
				if (!sim.local) {
					if (commander.side !== "spectators") {
						ui.go("quickscore");
					}
					if (ui.mode === "battle") {
						ui.go("quickscore");
					}
				}
				return this.uploadReplay();
			}

			drawThingsList() {
				var _, particle, ref1, ref2, ref3, thing, things;
				things = [];
				ref1 = this.things;
				for (_ in ref1) {
					thing = ref1[_];
					things.push(thing);
				}
				ref2 = this.particles;
				for (_ in ref2) {
					particle = ref2[_];
					things.push(particle);
				}
				ref3 = this.trails;
				for (_ in ref3) {
					particle = ref3[_];
					things.push(particle);
				}
				return things;
			}

			draw() {
				var ai,
					color,
					i,
					j,
					l,
					len,
					len1,
					len2,
					len3,
					m,
					o,
					p,
					player,
					q,
					ref1,
					ref2,
					ref3,
					thing,
					things;
				this.advance();
				if (
					typeof sim !== "undefined" && sim !== null
						? sim.ais
						: void 0
				) {
					ref1 = sim.ais;
					for (j = 0, len = ref1.length; j < len; j++) {
						ai = ref1[j];
						ai.draw();
					}
				}
				things = this.drawThingsList();
				things.sort(function (a, b) {
					return a.z - b.z;
				});
				for (l = 0, len1 = things.length; l < len1; l++) {
					thing = things[l];
					thing.draw();
				}
				color = [0, 0, 0, 0];
				ref2 = this.players;
				for (o = 0, len2 = ref2.length; o < len2; o++) {
					player = ref2[o];
					if (!player) {
						continue;
					}
					if (
						player.name !==
							(typeof commander !== "undefined" &&
							commander !== null
								? commander.name
								: void 0) &&
						player.side !== "spectators" &&
						player.side !== "dead" &&
						player.connected
					) {
						if (
							player.mouse[0] !== 0 &&
							player.mouse[1] !== 0 &&
							player._mouse
						) {
							m = [0, 0];
							color = [
								player.color[0],
								player.color[1],
								player.color[2],
								255,
							];
							v2.lerp(
								player._mouse,
								player.mouse,
								this.smoothFactor,
								m,
							);
							player.mouseTrail.push(m);
							while (player.mouseTrail.length > 10) {
								player.mouseTrail.shift();
							}
							ref3 = player.mouseTrail;
							for (
								i = q = 0, len3 = ref3.length;
								q < len3;
								i = ++q
							) {
								p = ref3[i];
								color[3] = 255 / (10 - i + 1);
								baseAtlas.drawSprite(
									"img/pip1.png",
									p,
									[1, 1],
									0,
									color,
								);
							}
							if (player.action) {
								baseAtlas.drawSprite(
									"img/pip1.png",
									m,
									[2, 2],
									0,
									player.color,
								);
							}
						}
					}
					if (
						player.name ===
						(typeof commander !== "undefined" && commander !== null
							? commander.name
							: void 0)
					) {
						player.selection = commander.selection;
						player.draw();
					}
				}
			}

			// uncomment this to debug
			//commander.draw()
			/* * uncomment this to debug
             for _, t of intp.things
                 #baseAtlas.drawSprite("img/pip1.png", t._pos2,  [1,1], 0, [0,255,0,100])
                 #baseAtlas.drawSprite("img/pip1.png", t._pos, [1,1], 0, [255,0,0,100])
                 if t.unit
                     for p in t.testIntp
                         baseAtlas.drawSprite("img/pip1.png", p, [.2,.2], 0, [255,0,0,100])
                     #for p in t.testStep
       *    baseAtlas.drawSprite("img/pip1.png", p, [.4,.4], 0, [0,255,0,100])
              */
			advance() {
				if (this.fast) {
					return this.advanceSnap();
				} else {
					return this.advanceSmooth();
				}
			}

			advanceSnap() {
				var i, id, j, len, ref1, ref2, thing, weapon;
				this.t = now();
				this.smoothFactor = 1;
				ref1 = this.things;
				for (id in ref1) {
					thing = ref1[id];
					v2.set(thing._pos, thing.pos);
					thing.rot = thing._rot;
					if (thing.weapons != null) {
						ref2 = thing.weapons;
						for (i = j = 0, len = ref2.length; j < len; i = ++j) {
							weapon = ref2[i];
							weapon.rot = weapon._rot;
						}
					}
				}
				return null;
			}

			advanceSmooth() {
				var a,
					angleDiff,
					difference,
					expectedLastStep,
					i,
					id,
					j,
					jumpDiff,
					len,
					part,
					ref1,
					ref2,
					ref3,
					thing,
					timeLastStep;
				this.t = now();
				/* * uncomment this to debug
         * instant
               if @dataQ.length > 0
                   @process(@dataQ.pop())
                */
				// low jitter
				if (this.dataQ.length > 0) {
					timeLastStep = this.t - this.stepTime;
					expectedLastStep = 1000 / 16;
					difference = timeLastStep / expectedLastStep;
					if (difference > 1 - this.dataQ.length * 0.1) {
						this.process(this.dataQ.pop());
					}
				}
				/* * uncomment this to debug
         * high jitter
               if @dataQ.length > 16
                   timeLastStep = @t - @stepTime
                   expectedLastStep = 1000/16
                   faster = 0
                   if @dataQ.length > 16
                       faster = (@dataQ.length-16)
                   console.log "difference", timeLastStep, expectedLastStep, @dataQ.length, faster
                   if timeLastStep > expectedLastStep - faster
                       @process(@dataQ.pop())
                */
				this.lastFrame += 1;
				a = this.lastFrame / this.avgFrame;
				this.smoothFactor = a;
				this.smoothStep = this.step + a;
				if (a > 1) {
					a = 1;
				}
				if (a < 0) {
					a = 0;
				}
				// if we are soo far behind stop everything from expanding
				if (this.smoothFactor > 10) {
					this.smoothFactor = 10;
				}
				ref1 = this.things;
				for (id in ref1) {
					thing = ref1[id];
					thing.pos[0] =
						thing._pos2[0] + (thing._pos[0] - thing._pos2[0]) * a;
					thing.pos[1] =
						thing._pos2[1] + (thing._pos[1] - thing._pos2[1]) * a;
					angleDiff = angleBetween(thing._rot2, thing._rot);
					thing.rot = thing._rot2 + angleDiff * a;
					if (thing.parts != null) {
						ref2 = thing.parts;
						for (i = j = 0, len = ref2.length; j < len; i = ++j) {
							part = ref2[i];
							angleDiff = angleBetween(part._rot2, part._rot);
							part.rot = part._rot2 + angleDiff * a;
						}
					}
					if (thing.jump != null) {
						jumpDiff = thing._jump2 - thing._jump;
						thing.jump = thing._jump + jumpDiff * a;
						if (thing.jump >= thing._jump2) {
							// don't extrapolate
							thing._jump = thing.jump = thing._jump2;
						}
					}
				}
				ref3 = this.particles;
				// particles
				for (id in ref3) {
					thing = ref3[id];
					thing.pos[0] =
						thing._pos2[0] + (thing._pos[0] - thing._pos2[0]) * a;
					thing.pos[1] =
						thing._pos2[1] + (thing._pos[1] - thing._pos2[1]) * a;
					angleDiff = angleBetween(thing._rot2, thing._rot);
					thing.rot = thing._rot2 + angleDiff * a;
				}
				return null;
			}

			recordReplay() {
				this.replay = "recording";
				return (this.replayFrames = []);
			}

			uploadReplay() {
				var data, frame;
				if (this.replay === "recording") {
					this.replay = "off";
					data = JSON.stringify(
						function () {
							var j, len, ref1, results;
							ref1 = this.replayFrames;
							results = [];
							for (j = 0, len = ref1.length; j < len; j++) {
								frame = ref1[j];
								results.push(dv2str(frame));
							}
							return results;
						}.call(this),
					);
					localStorage.replay = data;
				}
			}

			playReplay() {
				var data, frame;
				this.players = [];
				this.things = {};
				this.particles = {};
				this.winningSide = null;
				this.replay = "playing";
				this.replayStep = 0;
				data = localStorage.replay;
				this.replayFrames = (function () {
					var j, len, ref1, results;
					ref1 = JSON.parse(data);
					results = [];
					for (j = 0, len = ref1.length; j < len; j++) {
						frame = ref1[j];
						results.push(str2dv(frame));
					}
					return results;
				})();
				return (this.local = false);
			}

			recv(data) {
				this.dataQ.unshift(data);
				// we are really behind process stiff instalty
				while (this.dataQ.length > 32) {
					this.process(this.dataQ.pop());
				}
				return stats.simAdd();
			}

			think() {
				boundMethodCheck(this, ref);
			}

			debugDraw() {
				var j, l, ref1, ref2, results, x;
				for (
					x = j = 0, ref1 = this.prevWait;
					0 <= ref1 ? j < ref1 : j > ref1;
					x = 0 <= ref1 ? ++j : --j
				) {
					baseAtlas.drawSprite(
						"img/pip1.png",
						[
							20 + x * 40 - window.innerWidth,
							window.innerHeight - 120,
						],
						[1, 1],
						0,
						[0, 0, 0, 255],
					);
				}
				results = [];
				for (
					x = l = 0, ref2 = this.dataQ.length;
					0 <= ref2 ? l < ref2 : l > ref2;
					x = 0 <= ref2 ? ++l : --l
				) {
					results.push(
						baseAtlas.drawSprite(
							"img/pip1.png",
							[
								20 + x * 40 - window.innerWidth,
								window.innerHeight - 120,
							],
							[1, 1],
							0,
							[255, 255, 255, 255],
						),
					);
				}
				return results;
			}

			process(data) {
				var _,
					dt,
					id,
					j,
					k,
					kv,
					l,
					len,
					len1,
					len2,
					len3,
					len4,
					len5,
					len6,
					len7,
					len8,
					n,
					newObj,
					newThing,
					number,
					o,
					p,
					part,
					player,
					q,
					r,
					ref1,
					ref10,
					ref11,
					ref12,
					ref13,
					ref14,
					ref15,
					ref2,
					ref3,
					ref4,
					ref5,
					ref6,
					ref7,
					ref8,
					ref9,
					s,
					selection,
					t,
					thing,
					trail,
					u,
					unit,
					v,
					w,
					y,
					z;
				if (this.replay === "recording") {
					this.replayFrames.push(packet);
				}
				t = now();
				dt = t - this.stepTime;
				this.avgTime = this.avgTime * 0.9 + dt * 0.1;
				this.stepTime = t;
				this.avgFrame = this.avgFrame * 0.9 + this.lastFrame * 0.1;
				this.lastFrame = 0;
				// full update
				if (
					intp.players.length === 0 &&
					!data.fullUpdate &&
					commander
				) {
					print("waiting for full update");
					return;
				}
				intp.advanceStep = 0;
				if (data.fullUpdate) {
					intp.step = data.step;
				} else if (data.step != null) {
					if (intp.step + 1 === data.step) {
						intp.step += 1;
						intp.advanceStep = 1;
					} else {
						print("Over step, what about full update?");
						return;
					}
				}
				if (data.winningSide) {
					intp.winningSide = data.winningSide;
					onecup.refresh();
				}
				if (data.state) {
					intp.state = data.state;
					onecup.refresh();
				}
				if (intp.state === "starting") {
					this.gameStarted();
				}
				if (intp.state === "ended") {
					this.gameEnded();
				}
				if (data.serverType) {
					intp.serverType = data.serverType;
					onecup.refresh();
				}
				if (data.theme) {
					intp.theme = data.theme;
				}
				if (intp.countDown === 5 * 16 && !sim.local) {
					onecup.refresh();
				}
				if (data.countDown != null) {
					intp.countDown = data.countDown;
					if (intp.countDown % 16 === 0 && intp.state === "waiting") {
						onecup.refresh();
					}
				}
				// lock design and fleet mode when running a 1v1r
				designMode.locked =
					intp.serverType === "1v1t" &&
					intp.state === "running" &&
					commander.side !== "spectators";
				if (data.perf) {
					intp.perf = data.perf;
					if (control.perf) {
						onecup.refresh();
					}
				}
				ref1 = intp.things;
				// reset deltads & predict motion
				for (_ in ref1) {
					thing = ref1[_];
					//predict motion
					v2.add(thing._pos, thing.vel);
					v2.set(thing.pos, thing._pos2);
					thing._rot2 = thing.rot;
					if (thing.parts != null) {
						ref2 = thing.parts;
						for (j = 0, len = ref2.length; j < len; j++) {
							part = ref2[j];
							part._rot2 = part.rot;
						}
					}
				}
				ref3 = intp.players;
				for (l = 0, len1 = ref3.length; l < len1; l++) {
					player = ref3[l];
					player._mouse = player.mouse;
				}
				if (data.things) {
					ref4 = data.things;
					for (o = 0, len2 = ref4.length; o < len2; o++) {
						t = ref4[o];
						thing = null;
						part = null;
						newObj = false;
						for (q = 0, len3 = t.length; q < len3; q++) {
							kv = t[q];
							[k, v] = kv;
							switch (k) {
								case "thingId":
									thing = intp.things[v];
									if (!thing) {
										thing = {
											dummy: true, // dummy object which will be thrown away
										};
										newObj = true;
									}
									thing.id = v;
									part = null;
									newObj = false;
									break;
								case "spec":
									if (thing.dummy) {
										newThing = new types[thing.name](v);
										newThing.id = thing.id;
										newThing.name = thing.name;
										intp.things[newThing.id] = newThing;
										thing = newThing;
										newObj = true;
									}
									break;
								case "pos":
									if (newObj || thing._pos == null) {
										thing.pos = v2.create(v);
										thing._pos = v2.create(thing.pos);
										thing._pos2 = v2.create(thing.pos);
									} else {
										v2.set(v, thing._pos);
									}
									break;
								case "rot":
									if (newObj) {
										thing.rot = v;
										thing._rot = thing.rot;
										thing._rot2 = thing.rot;
										if (thing.weapons) {
											ref5 = thing.weapons;
											for (
												r = 0, len4 = ref5.length;
												r < len4;
												r++
											) {
												w = ref5[r];
												w.rot = thing.rot;
												w._rot = thing.rot;
												w._rot2 = thing.rot;
											}
										}
									} else {
										thing._rot = v;
									}
									break;
								case "jump":
									thing._jump = thing._jump2 || v;
									thing.jump = thing._jump2 = v;
									break;
								case "dead":
									thing.dead = v;
									if (thing.dead) {
										if (
											typeof thing.createDebree ===
											"function"
										) {
											thing.createDebree();
										}
									}
									break;
								case "partId":
									if (thing.parts) {
										part = thing.parts[v];
										newObj = false;
									} else {
										part = {};
									}
									break;
								case "partWorking":
									part.working = v;
									break;
								case "partTargetId":
									part.targetId = v;
									break;
								case "orders":
									thing.orders = v;
									if (thing.preOrders) {
										// clear per orders, when their timer expires
										thing.preOrders =
											thing.preOrders.filter(
												function (order) {
													return (
														order.step + 16 * 5 <
														sim.step
													);
												},
											);
									}
									break;
								default:
									thing[k] = v;
							}
						}
					}
				}
				if (data.players) {
					ref6 = data.players;
					for (s = 0, len5 = ref6.length; s < len5; s++) {
						p = ref6[s];
						player = null;
						for (u = 0, len6 = p.length; u < len6; u++) {
							kv = p[u];
							[k, v] = kv;
							if (k === "playerNumber") {
								while (intp.players.length <= v) {
									intp.players.push(new Player());
								}
								player = intp.players[v];
								player.number = v;
							} else {
								player[k] = v;
							}
							// for update of the UI when buildQ or validBar changes
							if (
								(k === "buildQ" || k === "validBar") &&
								commander.name === player.name
							) {
								onecup.refresh();
							}
						}
					}
				}
				ref7 = intp.things;
				// fix IDS
				for (_ in ref7) {
					thing = ref7[_];
					if (thing.targetId) {
						thing.target = intp.things[thing.targetId];
					}
					if (thing.originId) {
						thing.origin = intp.things[thing.originId];
					}
				}
				ref8 = this.things;
				for (id in ref8) {
					thing = ref8[id];
					if (typeof thing.clientTick === "function") {
						thing.clientTick();
					}
					if (thing.dead) {
						delete this.things[id];
					}
				}
				ref9 = this.players;
				for (
					number = y = 0, len7 = ref9.length;
					y < len7;
					number = ++y
				) {
					player = ref9[number];
					if (
						typeof commander !== "undefined" &&
						commander !== null &&
						(player != null ? player.ai : void 0) === false &&
						commander.name ===
							(player != null ? player.name : void 0)
					) {
						if (player.side) {
							commander.side = player.side;
						}
						if (player.money) {
							commander.money = player.money;
						}
						if (player.selection) {
							commander.selection = player.selection;
						}
						if (player.buildQ) {
							commander.buildQ = player.buildQ;
						}
						if (player.validBar) {
							commander.validBar = player.validBar;
						}
						if (player.rallyPoint) {
							commander.rallyPoint = player.rallyPoint;
						}
						commander.number = number;
						if (player.host != null) {
							commander.host = player.host;
						}
					}
					// fix player if no attriutes
					if (!player.name) {
						player.name = "no name";
					}
					if (!player.side) {
						player.side = "spectators";
					}
					if (!player.color) {
						player.color = [255, 0, 0, 255];
					}
				}
				ref10 = this.particles;
				// process particles
				for (id in ref10) {
					thing = ref10[id];
					if (thing.dead) {
						delete this.particles[id];
						continue;
					}
					if (!thing._pos) {
						thing._pos = v2.create(thing.pos);
					}
					if (!thing._pos2) {
						thing._pos2 = v2.create(thing.pos);
					}
					v2.set(thing.pos, thing._pos2);
					thing._rot2 = thing.rot;
					if (this.advanceStep === 1) {
						// when 0, that means sim is paused
						if (typeof thing.tick === "function") {
							thing.tick();
						}
						if (typeof thing.move === "function") {
							thing.move();
						}
					}
					v2.set(thing.pos, thing._pos);
					thing._rot = thing.rot;
				}
				ref11 = this.trails;
				// remove empty trails
				for (id in ref11) {
					trail = ref11[id];
					if (
						trail.trail.length === 0 &&
						this.things[trail.parentId] == null
					) {
						delete this.trails[id];
					}
				}
				if (this.state === "starting") {
					this.focusMap();
					this.state = "running";
					onecup.refresh();
				}
				if (this.state === "ended") {
					this.state = "waiting";
					onecup.refresh();
					if (this.winningSide === false) {
						playSound("sounds/drone/draw.wav");
					} else if (
						this.winningSide ===
						(typeof commander !== "undefined" && commander !== null
							? commander.side
							: void 0)
					) {
						playSound("sounds/drone/victory.wav");
					} else {
						playSound("sounds/drone/defeat.wav");
					}
					onecup.refresh();
				}
				if ((ref12 = onecup.lookup("#money-text")) != null) {
					ref12.innerHTML = buildBar.moneyText();
				}
				if ((ref13 = onecup.lookup("#money-income")) != null) {
					ref13.innerHTML = buildBar.moneyIncomeText();
				}
				buildBar.updateUnitBubble();
				if (
					typeof commander !== "undefined" && commander !== null
						? commander.selection
						: void 0
				) {
					// reselect upated units
					selection = [];
					ref14 = commander.selection;
					for (n = z = 0, len8 = ref14.length; z < len8; n = ++z) {
						unit = ref14[n];
						thing = this.things[unit.id];
						if (thing) {
							selection.push(thing);
						}
					}
					commander.selection = selection;
				}
				// if we have Ai and have some thing selected, we need to update the bubbles
				if (
					localStorage.useAi === "true" &&
					localStorage.aiGrid === "true"
				) {
					if (
						ui.mode === "battle" &&
						(typeof commander !== "undefined" && commander !== null
							? (ref15 = commander.selection) != null
								? ref15.length
								: void 0
							: void 0) > 0
					) {
						return onecup.refresh();
					}
				}
			}
		}

		Interpolator.prototype.sound = true;

		Interpolator.prototype.fast = false;

		Interpolator.prototype.replay = "off";

		return Interpolator;
	}.call(this);
}).call(this);
