// Generated by CoffeeScript 2.7.0
(function () {
	window.colors = {};

	colors.validate = function (a) {
		var b, i, j, ref;
		b = [0, 0, 0, 0];
		for (i = j = 0; j < 4; i = ++j) {
			if (Number.isInteger(a[i]) && 0 <= (ref = a[i]) && ref < 256) {
				b[i] = Math.floor(a[i]);
			}
		}
		return b;
	};

	colors.hsl2rgb = function (c) {
		var a, b, g, h, hue2rgb, l, p, q, r, s;
		[h, s, l, a] = c;
		if (s === 0) {
			r = g = b = l; // achromatic
		} else {
			hue2rgb = function (p, q, t) {
				if (t < 0) {
					t += 1;
				}
				if (t > 1) {
					t -= 1;
				}
				if (t < 1 / 6) {
					return p + (q - p) * 6 * t;
				}
				if (t < 1 / 2) {
					return q;
				}
				if (t < 2 / 3) {
					return p + (q - p) * (2 / 3 - t) * 6;
				}
				return p;
			};
			q = l < 0.5 ? l * (1 + s) : l + s - l * s;
			p = 2 * l - q;
			r = hue2rgb(p, q, h + 1 / 3);
			g = hue2rgb(p, q, h);
			b = hue2rgb(p, q, h - 1 / 3);
		}
		return [
			Math.round(r * 255),
			Math.round(g * 255),
			Math.round(b * 255),
			a,
		];
	};
}).call(this);
