// Generated by CoffeeScript 2.7.0
(function () {
	/*
  General Game Objects live here
  */
	var Explosion,
		_color,
		_focus,
		_offset,
		_pos,
		_size,
		_vec,
		anitSideColor,
		sideColor;

	_pos = v2.create(); // this are created as globals for speed

	_vec = v2.create(); // no need to allocate memory in tight loops

	window.Player = function () {
		class Player {
			constructor(id1) {
				this.id = id1;
				this.side = this.id;
				this.color = randColor(200);
				this.reset();
			}

			reset() {
				var n;
				this.money = sim.defaultMoney;
				this.mouse = [0, 0];
				this.rallyPoint = [0, 0];
				this.selection = [];
				this.buildQ = [];
				this.validBar = (function () {
					var j, results;
					results = [];
					for (n = j = 0; j < 10; n = ++j) {
						results.push(true);
					}
					return results;
				})();
				this.actions = 0;
				this.apm = 0;
				this.capps = 0;
				this.kills = 0;
				this.unitsBuilt = 0;
				this.moneyEarned = 0;
				return (this.mouseTrail = []);
			}

			earnMoney(amount) {
				amount *= this.moneyRatio;
				this.money += amount;
				return (this.moneyEarned += amount);
			}

			tick() {
				if (sim.step % 16 === 0) {
					if (this.gainsMoney && sim.gainsMoney) {
						this.earnMoney(10);
					}
					this.apm = this.actions / (sim.step / 16 / 60);
				}
				if (this.aiRules) {
					sim.timeIt("ai", () => {
						return doPlayerAIRules(this);
					});
				}
				return this.wave();
			}

			wave() {
				var build, i, j, len, n, ref, slot, waitTime;
				waitTime = 16 * 2;
				if (sim.step > waitTime && sim.step % 16 === 0) {
					build = false;
					ref = this.buildQ;
					for (i = j = 0, len = ref.length; j < len; i = ++j) {
						slot = ref[i];
						if (this.rqUnit(slot)) {
							this.buildQ[i] = null;
							build = true;
						} else {
							break;
						}
					}
					if (build) {
						return (this.buildQ = function () {
							var l, len1, ref1, results;
							ref1 = this.buildQ;
							results = [];
							for (l = 0, len1 = ref1.length; l < len1; l++) {
								n = ref1[l];
								if (n !== null) {
									results.push(n);
								}
							}
							return results;
						}.call(this));
					}
				}
			}

			rqUnit(slot) {
				var spawn, unit;
				if (sim.serverType === "survival" && this.side === "beta") {
					unit = survival.rqUnit(sim, this.number, slot);
				} else {
					spawn = sim.findSpawnPoint(this.side);
					if (spawn) {
						unit = sim.buildUnit(this.number, slot, spawn.pos);
						if (unit) {
							v2.random(unit.pos);
							v2.scale(
								unit.pos,
								100 + Math.random() * (spawn.radius - 100),
							);
							v2.add(unit.pos, spawn.pos);
						}
					}
				}
				if (unit) {
					this.unitsBuilt += 1;
					if (this.rallyPoint[0] !== 0 && this.rallyPoint[1] !== 0) {
						unit.setOrder({
							type: "Move",
							dest: this.rallyPoint,
							rally: true,
						});
					}
					return unit;
				}
				return null;
			}

		}

		Player.prototype.gainsMoney = true; // stop player from making money

		Player.prototype.ready = false;

		Player.prototype.actions = 0;

		Player.prototype.apm = 0;

		Player.prototype.capps = 0;

		Player.prototype.kills = 0;

		Player.prototype.unitsBuilt = 0;

		Player.prototype.moneyEarned = 0;

		Player.prototype.moneyRatio = 1;

		Player.prototype.aiRules = null;

		Player.prototype.host = false;

		Player.prototype.ai = false;

		return Player;
	}.call(this);

	_color = [0, 0, 0, 0];

	window.Particle = function () {
		class Particle {
			constructor() {
				this.id = sim.nid();
				this.color = [255, 255, 255, 255];
				this.life = 0;
				this.dead = false;
				this.z = Math.random();
				this.pos = v2.create();
				this.vel = v2.create();
				this._pos = v2.create();
				this._pos2 = v2.create();
				this.rot = 0;
			}

			move() {
				if (this.dead) {
					return;
				}
				v2.add(this.pos, this.vel);
				this.life += 1;
				if (this.life > this.maxLife) {
					return (this.dead = true);
				}
			}
		}

		Particle.prototype.image = null;

		Particle.prototype.size = [0.1, 0.1];

		Particle.prototype.maxLife = 60;

		Particle.prototype.radius = 1;

		return Particle;
	}.call(this);

	Explosion = function () {
		class Explosion extends Particle {}

		Explosion.prototype.image = "img/unitBar/pip1.png";

		Explosion.prototype.maxLife = 30;

		Explosion.prototype.radius = 2;

		Explosion.prototype.sound = "sounds/weapons/thud2.wav";

		Explosion.prototype.soundVolume = 0.1;

		return Explosion;
	}.call(this);

	window.Bullet = function () {
		class Bullet extends Particle {
			constructor() {
				super();
			}

			applyDamage() {
				// TODO REMOVE?
				return (this.dead = true);
			}

			move() {
				if (this.dead) {
					return;
				}
				v2.add(this.pos, this.vel);
				return (this.life += 1);
			}

			tick() {
				var exp;
				if (this.life > this.maxLife) {
					this.dead = true;
					return;
				}
				if (this.explode === false) {
					this.dead = true;
					return;
				}
				this.scan();
				if (this.dead) {
					exp = new types[this.hitExplosion]();
					exp.z = 1000;
					exp.pos = [this.pos[0], this.pos[1]];
					if (this.t !== null) {
						v2.add(exp.pos, v2.scale(this.vel, this.t));
					}
					exp.vel = [0, 0];
					exp.rot = 0;
					exp.radius = 0.75;
					return (sim.things[exp.id] = exp);
				}
			}

			scan() {
				sim.unitSpaces[otherSide(this.side)].findInRange(
					this.pos,
					this.radius + this.speed + 500,
					(unit) => {
						if (this.collide(unit)) {
							this.hitUnit(unit);
							if (this.hitsMultiple) {
								return false;
							}
							return true;
						}
						return false;
					},
				);
				if (this.hitsMissiles) {
					return sim.bulletSpaces[otherSide(this.side)].findInRange(
						this.pos,
						this.radius + this.speed + 100,
						(missle) => {
							if (missle.missile && this.collide(missle)) {
								this.hitMissle(missle);
								if (this.hitsMultiple) {
									return false;
								}
								return true;
							}
							return false;
						},
					);
				}
			}

			hitUnit(thing) {
				thing.applyDamage(this.damage);
				if (this.energyDamage) {
					thing.applyEnergyDamage(this.energyDamage);
				}
				if (!this.hitsMultiple) {
					return (this.dead = true);
				}
			}

			hitMissle(thing) {
				thing.life = thing.maxLife;
				return (thing.explode = false);
			}

			_collide(thing) {
				var distance, speed;
				distance = v2.distance(this.pos, thing.pos);
				speed = v2.mag(thing.vel) + v2.mag(this.vel);
				return distance < thing.radius; //+ speed
			}

			collide(thing) {
				var c, distance, r, speed, t1, t2, ta, tb, tc, v;
				if (!this.hitsCloak && thing.cloak && thing.cloaked()) {
					return false;
				}
				// check if we are inside the object
				distance = v2.distance(this.pos, thing.pos);
				if (distance < thing.radius + this.radius) {
					return true;
				}
				// check if we can't possibly hit
				speed = v2.mag(thing.vel) + v2.mag(this.vel);
				if (distance > thing.radius + this.radius + speed) {
					return false;
				}
				this.t = null;
				c = [0, 0];
				v2.sub(this.pos, thing.pos, c);
				v = [0, 0];
				v2.sub(this.vel, thing.vel, v);
				r = this.radius + thing.radius;
				ta = -(c[0] * v[0] + c[1] * v[1]);
				tb = Math.sqrt(
					r * r * (v[0] * v[0] + v[1] * v[1]) -
						Math.pow(c[0] * v[1] - c[1] * v[0], 2),
				);
				tc = v[0] * v[0] + v[1] * v[1];
				t1 = (ta - tb) / tc;
				t2 = (ta + tb) / tc;
				if (t1 > 0 && t1 < t2) {
					this.t = t1;
				}
				if (t2 > 0 && t2 < t1) {
					this.t = t2;
				}
				if (this.t !== null) {
					return this.t > 0 && this.t < 1;
				}
				return false;
			}

			__collide(thing) {
				var distance, j, len, part, ref, speed;
				if (!this.hitsCloak && thing.cloak && thing.cloaked()) {
					return false;
				}
				// check if we can't possibly hit
				speed = v2.mag(thing.vel) + v2.mag(this.vel);
				if (distance > thing.radius + this.radius + speed) {
					return false;
				}
				// check if we are inside the object
				distance = v2.distance(this.pos, thing.pos);
				if (distance < thing.radius + this.radius) {
					ref = thing.parts;
					for (j = 0, len = ref.length; j < len; j++) {
						part = ref[j];
						distance =
							v2.distance(this.pos, part.worldPos) -
							this.radius -
							10;
						if (distance < 0) {
							return true;
						}
					}
				}
				return false;
			}
		}

		Bullet.prototype.image = "img/unitBar/pip1.png";

		Bullet.prototype.damage = 1;

		Bullet.prototype.speed = 10;

		Bullet.prototype.size = [1, 1];

		Bullet.prototype.bullet = true;

		Bullet.prototype.radius = 10;

		Bullet.prototype.hitsMultiple = false;

		Bullet.prototype.hitExplosion = "HitExplosion";

		Bullet.prototype.side = null;

		Bullet.prototype.hitsCloak = false;

		return Bullet;
	}.call(this);

	_offset = v2.create();

	window.LaserBullet = function () {
		class LaserBullet extends Bullet {
			move() {}

			tick() {
				if (this.dead) {
					return;
				}
				this.life += 1;
				if (this.life > this.maxLife) {
					return (this.dead = true);
				}
			}
		}

		LaserBullet.prototype.image = "img/laser01.png";

		LaserBullet.prototype.size = [1, 1];

		LaserBullet.prototype.color = [179, 207, 255, 255];

		LaserBullet.prototype.speed = 2000;

		LaserBullet.prototype.damage = 2.5;

		LaserBullet.prototype.maxLife = 3;

		return LaserBullet;
	}.call(this);

	window.AoeBullet = function () {
		class AoeBullet extends Bullet {
			move() {
				if (this.dead) {
					return;
				}
				return v2.add(this.pos, this.vel);
			}

			tick() {
				var exp;
				this.life += 1;
				if (this.life > this.maxLife) {
					this.dead = true;
					if (this.explode) {
						// set the position on the last frame to be target pos
						exp = new types[this.explodeClass]();
						exp.z = 1000;
						exp.pos = [this.hitPos[0], this.hitPos[1]];
						exp.vel = [0, 0];
						exp.rot = 0;
						exp.aoe = this.aoe;
						exp.side = this.side;
						exp.damage = this.damage;
						return (sim.things[exp.id] = exp);
					}
				}
			}
		}

		AoeBullet.prototype.image = "img/unitBar/pip1.png";

		AoeBullet.prototype.size = [1, 1];

		AoeBullet.prototype.color = [100, 100, 100, 255];

		AoeBullet.prototype.speed = 30;

		AoeBullet.prototype.aoe = 50;

		AoeBullet.prototype.damage = 3;

		AoeBullet.prototype.explode = true;

		AoeBullet.prototype.explodeClass = "AoeExplosion";

		return AoeBullet;
	}.call(this);

	window.StraightMissile = function () {
		class StraightMissile extends Bullet {}

		StraightMissile.prototype.trailSize = 0.1;

		StraightMissile.prototype.trailTime = 94;

		return StraightMissile;
	}.call(this);

	window.TrackingMissile = function () {
		class TrackingMissile extends Bullet {
			move() {
				if (this.dead) {
					return;
				}
				if (
					this.target &&
					!this.target.dead &&
					!this.target.cloaked()
				) {
					v2.sub(this.target.pos, this.pos, this.vel);
					v2.norm(this.vel);
					v2.scale(this.vel, this.speed);
				}
				v2.add(this.pos, this.vel);
				this.rot = v2.angle(this.vel);
				return (this.life += 1);
			}

			tick() {
				var exp;
				if (this.life > this.maxLife) {
					this.dead = true;
					return;
				}
				sim.unitSpaces[otherSide(this.side)].findInRange(
					this.pos,
					this.radius + this.speed + 500,
					(unit) => {
						if (this.collide(unit)) {
							this.hitUnit(unit);
							return true;
						}
						return false;
					},
				);
				if (this.dead) {
					exp = new types.HitExplosion();
					exp.z = 1000;
					exp.pos = [this.pos[0], this.pos[1]];
					exp.vel = [0, 0];
					exp.rot = 0;
					exp.radius = 0.5;
					return (sim.things[exp.id] = exp);
				}
			}
		}

		TrackingMissile.prototype.image = "img/unitBar/pip1.png";

		TrackingMissile.prototype.size = [1, 1];

		TrackingMissile.prototype.color = [0, 0, 0, 255];

		TrackingMissile.prototype.speed = 15;

		TrackingMissile.prototype.damage = 8;

		TrackingMissile.prototype.radius = 10;

		TrackingMissile.prototype.missile = true;

		TrackingMissile.prototype.trailSize = 0.1;

		TrackingMissile.prototype.trailTime = 94;

		return TrackingMissile;
	}.call(this);

	types.Debree = function () {
		class Debree extends Particle {
			tick() {
				return (this.rot += this.vrot);
			}
		}

		Debree.prototype.image = null;

		Debree.prototype.maxLife = 16 * 5;

		Debree.prototype.radius = 2;

		Debree.prototype.size = [1, 1];

		return Debree;
	}.call(this);

	types.HitExplosion = function () {
		class HitExplosion extends Explosion {
			constructor() {
				super();
				this.frame = 0;
				this.hitImage = `parts/hit${choose([1, 2, 3, 4, 5])}.png`;
				this.rot = Math.random() * Math.PI * 2;
			}
		}

		HitExplosion.prototype.image = "img/fire02.png";

		HitExplosion.prototype.maxLife = 30;

		HitExplosion.prototype.radius = 2;

		HitExplosion.prototype.sound = "sounds/weapons/thud1.wav";

		HitExplosion.prototype.soundVolume = 0.1;

		return HitExplosion;
	}.call(this);

	types.SmallHitExplosion = function () {
		class SmallHitExplosion extends Explosion {
			constructor() {
				super();
				this.frame = 0;
				this.hitImage = `parts/hitAuto${choose([1, 2, 3])}.png`;
				this.rot = Math.random() * Math.PI * 2;
			}
		}

		SmallHitExplosion.prototype.sound = "sounds/weapons/thud4.wav";

		return SmallHitExplosion;
	}.call(this);

	types.RingHitExplosion = function () {
		class RingHitExplosion extends Explosion {
			constructor() {
				super();
				this.frame = 0;
			}
		}

		RingHitExplosion.prototype.image = "img/fire02.png";

		RingHitExplosion.prototype.maxLife = 30;

		return RingHitExplosion;
	}.call(this);

	types.ShipExplosion = function () {
		class ShipExplosion extends Explosion {
			constructor(sound) {
				super();
				this.sound = sound;
			}
		}

		ShipExplosion.prototype.image = "img/fire02.png";

		ShipExplosion.prototype.maxLife = 15;

		ShipExplosion.prototype.radius = 2;

		ShipExplosion.prototype.sound = "sounds/weapons/explode1.wav";

		ShipExplosion.prototype.soundVolume = 0.1;

		return ShipExplosion;
	}.call(this);

	types.AoeExplosion = function () {
		class AoeExplosion extends Explosion {
			tick() {
				if (!this.damaged) {
					this.damaged = true;
					return sim.unitSpaces[otherSide(this.side)].findInRange(
						this.pos,
						this.aoe + 500,
						(unit) => {
							var distance, fallOff;
							distance = Math.max(
								v2.distance(this.pos, unit.pos) - unit.radius,
								0,
							);
							if (distance < this.aoe) {
								fallOff = 1 - distance / this.aoe;
								if (typeof unit.applyDamage === "function") {
									unit.applyDamage(this.damage * fallOff);
								}
								if (this.energyDamage > 1) {
									if (
										typeof unit.applyEnergyDamage ===
										"function"
									) {
										unit.applyEnergyDamage(
											this.energyDamage * fallOff,
										);
									}
								}
								if (this.burnAmount > 1) {
									if (
										typeof unit.applyBurnAmount ===
										"function"
									) {
										unit.applyBurnAmount(
											this.burnAmount * fallOff,
										);
									}
								}
							}
							return false;
						},
					);
				}
			}
		}

		AoeExplosion.prototype.image = "img/point02.png";

		AoeExplosion.prototype.maxLife = 10;

		AoeExplosion.prototype.radius = 2;

		AoeExplosion.prototype.sound = "sounds/weapons/thud3.wav";

		AoeExplosion.prototype.soundVolume = 0.5;

		AoeExplosion.prototype.damage = 0;

		AoeExplosion.prototype.aoe = 0;

		return AoeExplosion;
	}.call(this);

	types.FrameExplosion = function () {
		class FrameExplosion extends Explosion {
			constructor() {
				super();
			}
		}

		FrameExplosion.prototype.image = "img/fx/fire1/f#.png";

		FrameExplosion.prototype.nFrames = 8;

		FrameExplosion.prototype.maxLife = 16;

		FrameExplosion.prototype.radius = 2;

		FrameExplosion.prototype.sound = "sounds/weapons/explode1.wav";

		FrameExplosion.prototype.soundVolume = 0.1;

		return FrameExplosion;
	}.call(this);

	_focus = v2.create();

	_size = v2.create();

	types.Rock = function () {
		class Rock {
			constructor() {
				this.image = "img/rocks/srock01.png";
				if (typeof sim !== "undefined" && sim !== null) {
					this.color = sim.theme.fillColor;
				}
				this.id = sim.nid();
				this.dead = false;
				this.hp = this.maxHP;
				this.pos = v2.create([0, 0]);
				this.vel = v2.create([0, 0]);
				this.rot = 0;
				this.size = v2.create([1, 1]);
			}

			move() {}
		}

		Rock.prototype.image = "img/unitBar/pip1.png";

		Rock.prototype.size = [1, 1];

		Rock.prototype.static = true;

		Rock.prototype.maxHP = 1000;

		return Rock;
	}.call(this);

	sideColor = function (side) {
		var color, mySide;
		mySide =
			typeof commander !== "undefined" && commander !== null
				? commander.side
				: void 0;
		if (mySide !== "beta") {
			mySide = "alpha";
		}
		if (mySide === side) {
			color = [230, 230, 230, 255];
		} else {
			color = [20, 20, 20, 255];
		}
		return color;
	};

	anitSideColor = function (side) {
		var color, mySide;
		mySide =
			typeof commander !== "undefined" && commander !== null
				? commander.side
				: void 0;
		if (mySide === "spectators") {
			mySide = "alpha";
		}
		if (mySide !== side) {
			color = [230, 230, 230, 255];
		} else {
			color = [20, 20, 20, 255];
		}
		return color;
	};

	types.CommandPoint = function () {
		class CommandPoint {
			constructor() {
				this.id = sim.nid();
				this.dead = false;
				this.z = 0.01;
				this.hp = this.maxHP;
				this.pos = v2.create(0, 0);
				this.vel = [0, 0];
				this.rot = 0;
				this.color = [255, 255, 255, 255];
				this.side = "neutral";
				this.capping = 0;
			}

			tick() {
				var _,
					distance,
					id,
					j,
					k,
					len,
					p,
					player,
					playerOnPoint,
					ref,
					ref1,
					results,
					sides,
					thing;
				if (sim.state !== "running") {
					return;
				}
				// tick every second only
				if (sim.step % 16 === 0) {
					// give money to players
					if (this.side !== null) {
						ref = sim.players;
						for (_ in ref) {
							p = ref[_];
							if (p && p.side === this.side) {
								if (p.gainsMoney && sim.gainsMoney) {
									p.earnMoney(1);
								}
							}
						}
					}
					sides = {};
					playerOnPoint = [];
					ref1 = sim.things;
					for (id in ref1) {
						thing = ref1[id];
						if (thing.unit && thing.canCapture) {
							distance = v2.distance(this.pos, thing.pos);
							if (distance < this.radius) {
								sides[thing.side] = true;
								player = sim.players[thing.owner];
								if (player) {
									playerOnPoint.push(player);
								}
							}
						}
					}
					sides = (function () {
						var results;
						results = [];
						for (k in sides) {
							results.push(k);
						}
						return results;
					})();
					if (sides.length === 1 && this.side !== sides[0]) {
						this.capping += 1;
						if (this.capping >= this.maxCapp) {
							this.side = sides[0];
							sim.captures += 1;
							this.capping = 0;
							this.bonus(this.side, 100);
							results = [];
							for (
								j = 0, len = playerOnPoint.length;
								j < len;
								j++
							) {
								p = playerOnPoint[j];
								results.push((p.capps += 1));
							}
							return results;
						}
					} else {
						if (this.capping > 0) {
							return (this.capping -= 1);
						}
					}
				}
			}

			bonus(side, amount) {
				var _, p, ref, results;
				ref = sim.players;
				results = [];
				for (_ in ref) {
					p = ref[_];
					if (p.side === this.side) {
						if (p.gainsMoney && sim.gainsMoney) {
							results.push(p.earnMoney(amount));
						} else {
							results.push(void 0);
						}
					} else {
						results.push(void 0);
					}
				}
				return results;
			}
		}

		CommandPoint.prototype.image = "img/point02.png";

		// TODO: Oscar - Change sliceImage to modify the capture progress bar
		CommandPoint.prototype.sliceImage = "img/map/slice02.png";

		CommandPoint.prototype.maxHP = 1000;

		CommandPoint.prototype.size = [1, 1];

		CommandPoint.prototype.maxHP = 1000;

		CommandPoint.prototype.radius = 250;

		CommandPoint.prototype.commandPoint = true;

		CommandPoint.prototype.capping = 0;

		// TODO: Oscar - Mess with maxCapp to change CP times, it breaks the visuals though
		CommandPoint.prototype.maxCapp = 10;

		return CommandPoint;
	}.call(this);

	types.SpawnPoint = function () {
		class SpawnPoint {
			constructor() {
				this.id = sim.nid();
				this.dead = false;
				this.z = 0.01;
				this.hp = this.maxHP;
				this.pos = v2.create(0, 0);
				this.vel = [0, 0];
				this.rot = 0;
				this.color = [255, 255, 255, 255];
				this.side = "neutral";
			}
		}

		SpawnPoint.prototype.image = "";

		SpawnPoint.prototype.sliceImage = "img/map/spawnSlice.png";

		SpawnPoint.prototype.maxHP = 1000;

		SpawnPoint.prototype.size = [1, 1];

		SpawnPoint.prototype.maxHP = 1000;

		SpawnPoint.prototype.static = true;

		SpawnPoint.prototype.radius = 400;

		SpawnPoint.prototype.spawn = true;

		SpawnPoint.prototype.side = null;

		return SpawnPoint;
	}.call(this);
}).call(this);
