// Generated by CoffeeScript 2.7.0
(function () {
	window.print = function (...args) {
		return console.log(...args);
	};

	window.choose = function (list) {
		return list[Math.floor(Math.random() * list.length)];
	};

	window.chooseInt = function (a, b) {
		return Math.floor(a + Math.random() * (b - a));
	};

	window.json = {
		dumps: JSON.stringify,
		loads: JSON.parse,
	};

	window.now = function () {
		var n, s;
		if (typeof process !== "undefined" && process !== null) {
			[s, n] = process.hrtime();
			return (s * 1000000 + n / 1000) / 1000;
		} else {
			return performance.now();
		}
	};

	window.randColor = function (a) {
		return [
			Math.floor(a + (255 - a) * Math.random()),
			Math.floor(a + (255 - a) * Math.random()),
			Math.floor(a + (255 - a) * Math.random()),
			255,
		];
	};

}).call(this);
